defmodule Fathom.DjangoUdfCompatTest do
  @moduledoc """
  Expert review 2026-08-01 **#19**: Django's SQLite backend registers ~35 Python UDFs on every
  *client* connection. Under `django-libsql` the SQL crosses the wire and is compiled by
  **fathom's** SQLite, where those functions did not exist — so ordinary querysets
  (`__year`, `__date`, `__regex`, `Trunc*`, `F()` arithmetic on a `DurationField`) raised
  `OperationalError` against the flagship "point an unchanged Django app at it" claim, while basic
  CRUD worked. That asymmetry is exactly why the working slice and both TPC harnesses never caught
  it: TPC-B and TPC-C use only builtins.

  **This file used to be the tracked list of what was MISSING. As of 2026-08-05 it is the
  behavioural suite for what is SUPPLIED.** All 54 functions Django needs now resolve: 19 from
  SQLite's own `SQLITE_ENABLE_MATH_FUNCTIONS` build, and 35 from `fathom_udf`, the Rust loadable
  extension in `native/fathom_udf` (see `Fathom.Shard.Extension` for the load-and-relock sequence
  and `docs/quickstart-django.md` for the operator view).

  ## What is tested WHERE, and why it is split

  This file drives the functions **over the real connection path** — `Fathom.Shard.Connection`,
  the same code a Hrana stream uses — so it covers the wiring: that the extension loads, that it
  loads on tenant and read-only handles too, and that results survive the round trip as the right
  SQLite type. It asserts a representative result per family rather than exhaustive values.

  Exhaustive value-level agreement with Django lives in the Rust crate, where
  `native/fathom_udf/tests/oracle.rs` replays **12,501 cases generated by running Django's own
  `_sqlite_*` functions** (`tests/oracle/generate_cases.py`). That is the right place for it: it
  needs no database, runs in milliseconds, and its expectations are generated rather than
  hand-written. Seven real bugs came out of it that hand-written expectations had missed —
  including `django_format_dtdelta` returning text where Django returns a number, and
  `date - timedelta` moving the date a day when it should not.

  Duplicating that matrix here would be slower, no more correct, and a second place to update.
  """
  use ExUnit.Case, async: false

  alias Fathom.Shard.Connection
  alias Fathom.Shard.Extension

  # The 19 Django needs that SQLite already provides. Worth keeping pinned: a future build without
  # SQLITE_ENABLE_MATH_FUNCTIONS would silently break Django's Power/Log/trig lookups, and nothing
  # else would catch it.
  @from_sqlite_build [
    {"ACOS", "SELECT ACOS(0.5)"},
    {"ASIN", "SELECT ASIN(0.5)"},
    {"ATAN", "SELECT ATAN(0.5)"},
    {"ATAN2", "SELECT ATAN2(1,1)"},
    {"CEILING", "SELECT CEILING(1.2)"},
    {"COS", "SELECT COS(0)"},
    {"DEGREES", "SELECT DEGREES(1)"},
    {"EXP", "SELECT EXP(1)"},
    {"FLOOR", "SELECT FLOOR(1.2)"},
    {"LN", "SELECT LN(1)"},
    {"LOG", "SELECT LOG(2,8)"},
    {"MOD", "SELECT MOD(5,2)"},
    {"PI", "SELECT PI()"},
    {"POWER", "SELECT POWER(2,3)"},
    {"RADIANS", "SELECT RADIANS(90)"},
    {"SIN", "SELECT SIN(0)"},
    {"SQRT", "SELECT SQRT(4)"},
    {"TAN", "SELECT TAN(0)"},
    {"SIGN", "SELECT SIGN(-2)"}
  ]

  # The 35 supplied by native/fathom_udf.
  @from_extension [
    {"LPAD", "SELECT LPAD('x',3,'0')"},
    {"RPAD", "SELECT RPAD('x',3,'0')"},
    {"REPEAT", "SELECT REPEAT('x',3)"},
    {"REVERSE", "SELECT REVERSE('abc')"},
    {"MD5", "SELECT MD5('x')"},
    {"SHA1", "SELECT SHA1('x')"},
    {"SHA224", "SELECT SHA224('x')"},
    {"SHA256", "SELECT SHA256('x')"},
    {"SHA384", "SELECT SHA384('x')"},
    {"SHA512", "SELECT SHA512('x')"},
    {"regexp", "SELECT 'abc' REGEXP '^a'"},
    {"BITXOR", "SELECT BITXOR(1,2)"},
    {"COT", "SELECT COT(1)"},
    {"UUIDV4", "SELECT UUIDV4()"},
    {"UUIDV7", "SELECT UUIDV7()"},
    {"RAND", "SELECT RAND()"},
    {"STDDEV_POP", "SELECT STDDEV_POP(v) FROM (SELECT 1 AS v UNION SELECT 3)"},
    {"STDDEV_SAMP", "SELECT STDDEV_SAMP(v) FROM (SELECT 1 AS v UNION SELECT 3)"},
    {"VAR_POP", "SELECT VAR_POP(v) FROM (SELECT 1 AS v UNION SELECT 3)"},
    {"VAR_SAMP", "SELECT VAR_SAMP(v) FROM (SELECT 1 AS v UNION SELECT 3)"},
    {"ANY_VALUE", "SELECT ANY_VALUE(v) FROM (SELECT 1 AS v UNION SELECT 3)"},
    {"BIT_AND", "SELECT BIT_AND(v) FROM (SELECT 1 AS v UNION SELECT 3)"},
    {"BIT_OR", "SELECT BIT_OR(v) FROM (SELECT 1 AS v UNION SELECT 3)"},
    {"BIT_XOR", "SELECT BIT_XOR(v) FROM (SELECT 1 AS v UNION SELECT 3)"},
    {"django_time_extract", "SELECT django_time_extract('hour','12:00:00')"},
    {"django_time_trunc", "SELECT django_time_trunc('hour','12:00:00',NULL,NULL)"},
    {"django_time_diff", "SELECT django_time_diff('12:00:00','11:00:00')"},
    {"django_timestamp_diff",
     "SELECT django_timestamp_diff('2026-08-05 12:00:00','2026-08-05 11:00:00')"},
    {"django_format_dtdelta", "SELECT django_format_dtdelta('+',1,2)"},
    {"django_date_extract", "SELECT django_date_extract('year','2026-08-05')"},
    {"django_date_trunc", "SELECT django_date_trunc('month','2026-08-05',NULL,NULL)"},
    {"django_datetime_cast_date",
     "SELECT django_datetime_cast_date('2026-08-05 12:00:00',NULL,NULL)"},
    {"django_datetime_cast_time",
     "SELECT django_datetime_cast_time('2026-08-05 12:00:00',NULL,NULL)"},
    {"django_datetime_extract",
     "SELECT django_datetime_extract('hour','2026-08-05 12:00:00',NULL,NULL)"},
    {"django_datetime_trunc",
     "SELECT django_datetime_trunc('day','2026-08-05 12:00:00',NULL,NULL)"}
  ]

  # Builtins Django also leans on. If one of these regresses the problem is the engine, not #19,
  # and the two failures look identical from Django's side.
  @builtins [
    {"LOWER", "SELECT LOWER('ABC')"},
    {"strftime", "SELECT strftime('%Y', '2026-08-05')"},
    {"json_extract", "SELECT json_extract('{\"a\":1}', '$.a')"},
    {"ABS", "SELECT ABS(-1)"}
  ]

  setup context do
    path = Path.join(System.tmp_dir!(), "fathom_udf_#{System.unique_integer([:positive])}.db")
    opts = Map.get(context, :open_opts, [])
    {:ok, conn} = Connection.open(path, opts)

    on_exit(fn ->
      Connection.close(conn)
      for s <- ["", "-wal", "-shm"], do: File.rm(path <> s)
    end)

    %{conn: conn, path: path}
  end

  defp one(conn, sql) do
    case Connection.query(conn, sql, []) do
      {:ok, %{rows: [[value] | _]}} -> value
      {:ok, %{rows: []}} -> :no_rows
      {:error, reason} -> {:error, reason}
    end
  end

  defp available?(conn, sql) do
    case Connection.query(conn, sql, []) do
      {:ok, _} -> true
      {:error, reason} -> not (inspect(reason) =~ "no such function")
    end
  end

  # ------------------------------------------------------------------------------------------
  # the extension is actually loaded
  # ------------------------------------------------------------------------------------------

  test "the extension artifact is present — everything below is vacuous without it" do
    # Asserted FIRST and explicitly. Every functional test in this file would otherwise "pass" by
    # reporting a missing function as an acceptable outcome, and the suite would go green on a
    # machine where `mix compile.fathom_udf` had silently skipped for lack of cargo.
    assert Extension.available?(),
           """
           priv/sqlite_ext/ has no extension, so Django's UDFs are NOT installed.
           Run `mix compile` with cargo on PATH (https://rustup.rs).
           Looked for: #{Extension.default_path()}
           """
  end

  test "the builtins Django relies on all resolve", %{conn: conn} do
    for {name, sql} <- @builtins do
      assert available?(conn, sql),
             "builtin #{name} is missing — that is an engine problem, not #19"
    end
  end

  test "the 19 functions SQLite itself provides still resolve", %{conn: conn} do
    missing = for {name, sql} <- @from_sqlite_build, not available?(conn, sql), do: name

    assert missing == [],
           "these used to resolve and no longer do: #{inspect(missing)} — check whether the " <>
             "SQLite build lost SQLITE_ENABLE_MATH_FUNCTIONS"
  end

  test "all 35 functions the extension supplies resolve", %{conn: conn} do
    missing = for {name, sql} <- @from_extension, not available?(conn, sql), do: name

    assert missing == [],
           "the extension loaded but these are missing: #{inspect(missing)}"
  end

  test "the inventory is still the full 54 Django needs" do
    assert length(@from_sqlite_build) == 19
    assert length(@from_extension) == 35
    assert length(@from_sqlite_build) + length(@from_extension) == 54
  end

  # ------------------------------------------------------------------------------------------
  # results, not just presence
  # ------------------------------------------------------------------------------------------
  #
  # A UDF returning the WRONG value is worse than a missing one: Django does not raise, it just
  # reports incorrect data. Presence tests alone would not notice.

  describe "date/time truncation" do
    test "django_date_trunc over the lookup types", %{conn: conn} do
      cases = [
        {"year", "2026-01-01"},
        {"quarter", "2026-07-01"},
        {"month", "2026-08-01"},
        {"day", "2026-08-05"},
        # 2026-08-05 is a Wednesday; Django's week starts Monday.
        {"week", "2026-08-03"}
      ]

      for {lookup, expected} <- cases do
        assert one(conn, "SELECT django_date_trunc('#{lookup}','2026-08-05',NULL,NULL)") ==
                 expected,
               "date_trunc #{lookup}"
      end
    end

    test "django_datetime_trunc over the lookup types", %{conn: conn} do
      cases = [
        {"year", "2026-01-01 00:00:00"},
        {"quarter", "2026-07-01 00:00:00"},
        {"month", "2026-08-01 00:00:00"},
        {"week", "2026-08-03 00:00:00"},
        {"day", "2026-08-05 00:00:00"},
        {"hour", "2026-08-05 13:00:00"},
        {"minute", "2026-08-05 13:45:00"},
        {"second", "2026-08-05 13:45:59"}
      ]

      for {lookup, expected} <- cases do
        sql =
          "SELECT django_datetime_trunc('#{lookup}','2026-08-05 13:45:59.123456',NULL,NULL)"

        assert one(conn, sql) == expected, "datetime_trunc #{lookup}"
      end
    end

    test "django_time_trunc", %{conn: conn} do
      for {lookup, expected} <- [
            {"hour", "13:00:00"},
            {"minute", "13:45:00"},
            {"second", "13:45:59"}
          ] do
        assert one(conn, "SELECT django_time_trunc('#{lookup}','13:45:59.5',NULL,NULL)") ==
                 expected
      end
    end

    test "an unsupported lookup type errors rather than returning something plausible", %{
      conn: conn
    } do
      assert {:error, reason} =
               Connection.query(
                 conn,
                 "SELECT django_date_trunc('fortnight','2026-08-05',NULL,NULL)",
                 []
               )

      refute inspect(reason) =~ "no such function"
    end
  end

  describe "extraction" do
    test "django_date_extract and django_datetime_extract agree with Django", %{conn: conn} do
      dt = "2026-08-05 13:45:59.123456"

      cases = [
        {"year", 2026},
        {"month", 8},
        {"day", 5},
        {"hour", 13},
        {"minute", 45},
        {"second", 59},
        {"microsecond", 123_456},
        {"quarter", 3},
        {"week", 32},
        {"iso_year", 2026},
        {"iso_week_day", 3},
        # Django's week_day is Sunday==1 … Saturday==7, so a Wednesday is 4.
        {"week_day", 4}
      ]

      for {lookup, expected} <- cases do
        assert one(conn, "SELECT django_datetime_extract('#{lookup}','#{dt}',NULL,NULL)") ==
                 expected,
               "datetime_extract #{lookup}"
      end

      # django_date_extract is arity 2 and is the SAME Python function.
      assert one(conn, "SELECT django_date_extract('year','2026-08-05')") == 2026
      assert one(conn, "SELECT django_date_extract('week_day','2026-08-09')") == 1, "a Sunday"
    end

    test "django_time_extract", %{conn: conn} do
      assert one(conn, "SELECT django_time_extract('hour','13:45:59.5')") == 13
      assert one(conn, "SELECT django_time_extract('minute','13:45:59.5')") == 45
      assert one(conn, "SELECT django_time_extract('second','13:45:59.5')") == 59
      assert one(conn, "SELECT django_time_extract('microsecond','13:45:59.5')") == 500_000
    end
  end

  describe "timezone-aware behaviour — the reason this needed a bundled tzdata" do
    test "truncating to a day converts into the target zone first", %{conn: conn} do
      # 2026-08-05 03:30 UTC is 2026-08-04 23:30 in New York. Truncating to the day must give the
      # FOURTH. This is the bug a tz-ignoring implementation ships, and it is invisible until a
      # user near midnight reports that their "today" totals are wrong.
      sql =
        "SELECT django_datetime_trunc('day','2026-08-05 03:30:00','America/New_York','UTC')"

      assert one(conn, sql) == "2026-08-04 00:00:00"

      assert one(
               conn,
               "SELECT django_datetime_cast_date('2026-08-05 03:30:00','America/New_York','UTC')"
             ) == "2026-08-04"
    end

    test "extracting a year across a new-year boundary in another zone", %{conn: conn} do
      assert one(
               conn,
               "SELECT django_datetime_extract('year','2027-01-01 02:00:00','America/New_York','UTC')"
             ) == 2026

      assert one(
               conn,
               "SELECT django_datetime_extract('year','2026-12-31 20:00:00','Asia/Tokyo','UTC')"
             ) == 2027
    end

    test "half-hour and quarter-hour zone offsets", %{conn: conn} do
      # Kolkata is +05:30; a zone table storing whole hours gets this wrong.
      assert one(
               conn,
               "SELECT django_datetime_cast_time('2026-08-05 00:00:00','Asia/Kolkata','UTC')"
             ) == "05:30:00"

      # Chatham is +12:45 (+13:45 in DST) — the only quarter-hour zone in common use.
      assert one(
               conn,
               "SELECT django_datetime_cast_time('2026-08-05 00:00:00','Pacific/Chatham','UTC')"
             ) == "12:45:00"
    end

    test "the DST gap does not error", %{conn: conn} do
      # 2026-03-08 02:30 America/New_York does not exist (the clock jumps 02:00 -> 03:00). Python
      # resolves it with the pre-transition offset. An implementation that unwraps chrono's
      # LocalResult::None panics here — twice a year, per zone.
      assert one(
               conn,
               "SELECT django_datetime_cast_time('2026-03-08 02:30:00','UTC','America/New_York')"
             ) == "07:30:00"
    end

    test "the ambiguous DST hour takes the first occurrence", %{conn: conn} do
      # 2026-11-01 01:30 happens twice in New York. Python's fold=0 picks the first (EDT).
      assert one(
               conn,
               "SELECT django_datetime_cast_time('2026-11-01 01:30:00','UTC','America/New_York')"
             ) == "05:30:00"
    end

    test "an offset baked into the tzname is applied", %{conn: conn} do
      # Django encodes `Trunc(..., tzinfo=...)` offsets as "Zone+HH:MM".
      assert one(
               conn,
               "SELECT django_datetime_cast_time('2026-08-05 12:00:00','UTC+05:00','UTC')"
             ) == "17:00:00"
    end

    test "an unknown zone errors instead of silently passing the value through", %{conn: conn} do
      assert {:error, reason} =
               Connection.query(
                 conn,
                 "SELECT django_datetime_cast_date('2026-08-05 00:00:00','Mars/Olympus','UTC')",
                 []
               )

      refute inspect(reason) =~ "no such function"
    end
  end

  describe "durations" do
    test "django_time_diff and django_timestamp_diff are signed microseconds", %{conn: conn} do
      assert one(conn, "SELECT django_time_diff('12:00:00','11:00:00')") == 3_600_000_000
      assert one(conn, "SELECT django_time_diff('11:00:00','12:00:00')") == -3_600_000_000

      assert one(
               conn,
               "SELECT django_timestamp_diff('2026-08-06 00:00:00','2026-08-05 00:00:00')"
             ) == 86_400_000_000
    end

    test "django_format_dtdelta returns Python's timedelta string for + and -", %{conn: conn} do
      assert one(conn, "SELECT django_format_dtdelta('+',1,2)") == "0:00:00.000003"

      # Python normalizes a negative duration to a negative DAY count plus a positive time, so this
      # is not "-0:00:00.000003". Django's parse_duration expects exactly this shape on the way
      # back.
      assert one(conn, "SELECT django_format_dtdelta('-',1,4)") == "-1 day, 23:59:59.999997"
    end

    test "django_format_dtdelta returns a NUMBER for * and /, not text", %{conn: conn} do
      # Django only str()s the + and - results. Returning '12' as TEXT here would make
      # `WHERE duration * 2 = 12` stop matching, because SQLite does not compare text to an integer
      # as equal. Found by the generated oracle, not by reading the source.
      assert one(conn, "SELECT django_format_dtdelta('*',3,4)") === 12
      assert one(conn, "SELECT django_format_dtdelta('/',9,2)") === 4.5
      # Python 3 true division is a float even when it divides evenly.
      assert one(conn, "SELECT django_format_dtdelta('/',8,2)") === 4.0

      assert one(conn, "SELECT typeof(django_format_dtdelta('*',3,4))") == "integer"
      assert one(conn, "SELECT typeof(django_format_dtdelta('/',9,2))") == "real"
      assert one(conn, "SELECT typeof(django_format_dtdelta('+',1,2))") == "text"
    end
  end

  describe "text and hashes" do
    test "padding matches Django, including its truncating behaviour", %{conn: conn} do
      assert one(conn, "SELECT LPAD('x',3,'0')") == "00x"
      assert one(conn, "SELECT RPAD('x',3,'0')") == "x00"
      # Django's LPAD/RPAD TRUNCATE when the text is already long enough.
      assert one(conn, "SELECT LPAD('abcdef',3,'0')") == "abc"
      assert one(conn, "SELECT RPAD('abcdef',3,'0')") == "abc"
      # Multi-character fill is repeated then cut to the gap.
      assert one(conn, "SELECT LPAD('x',5,'ab')") == "ababx"
    end

    test "text functions work on code points, not bytes", %{conn: conn} do
      assert one(conn, "SELECT LPAD('é',3,'0')") == "00é"
      assert one(conn, "SELECT REVERSE('héllo')") == "olléh"
      assert one(conn, "SELECT REVERSE('a🙂b')") == "b🙂a"
      assert one(conn, "SELECT REPEAT('日',3)") == "日日日"
    end

    test "hashes match hashlib over UTF-8", %{conn: conn} do
      assert one(conn, "SELECT MD5('x')") == "9dd4e461268c8034f5c8564e155c67a6"
      assert one(conn, "SELECT SHA1('x')") == "11f6ad8ec52a2984abaafd7c3b516503785c2072"

      assert one(conn, "SELECT SHA256('x')") ==
               "2d711642b726b04401627ca9fbac32f5c8530fb1903cc4db02258717921a4881"

      assert one(conn, "SELECT SHA256('é')") ==
               "4a99557e4033c3539de2eb65472017cad5f9557f7a0625a09f1c3f6e2ba69c4c"

      assert String.length(one(conn, "SELECT SHA512('x')")) == 128
    end

    test "regexp uses the pattern-first argument order the REGEXP operator implies", %{conn: conn} do
      # SQLite rewrites `X REGEXP Y` as `regexp(Y, X)` — pattern first. Getting this backwards
      # produces a function that works on symmetric test data and is wrong everywhere else.
      assert one(conn, "SELECT 'abc' REGEXP '^a'") == 1
      assert one(conn, "SELECT 'abc' REGEXP '^b'") == 0
      assert one(conn, "SELECT regexp('^a','abc')") == 1
      assert one(conn, "SELECT 'Hello' REGEXP '[A-Z]'") == 1
      # A constant pattern is compiled once per statement, so a multi-row scan still works.
      assert one(
               conn,
               "SELECT COUNT(*) FROM (SELECT 'aa' v UNION SELECT 'ab' UNION SELECT 'ba') WHERE v REGEXP '^a'"
             ) ==
               2
    end

    test "uuid generators return Django's 32-char dashless hex", %{conn: conn} do
      for fun <- ["UUIDV4", "UUIDV7"] do
        value = one(conn, "SELECT #{fun}()")
        assert String.length(value) == 32, "#{fun} should be uuid4().hex-shaped"
        refute value =~ "-"
        assert value =~ ~r/^[0-9a-f]{32}$/
      end

      # Non-deterministic: two calls in one statement must differ.
      assert one(conn, "SELECT UUIDV4() = UUIDV4()") == 0
    end

    test "RAND is a float in [0,1), not SQLite's 64-bit random()", %{conn: conn} do
      value = one(conn, "SELECT RAND()")
      assert is_float(value)
      assert value >= 0.0 and value < 1.0
    end
  end

  describe "aggregates" do
    setup %{conn: conn} do
      :ok = Connection.exec(conn, "CREATE TABLE t (v INTEGER)")

      {:ok, _} =
        Connection.query(conn, "INSERT INTO t (v) VALUES (2),(4),(4),(4),(5),(5),(7),(9)", [])

      :ok
    end

    test "variance and standard deviation match Python's statistics module", %{conn: conn} do
      # statistics.pvariance([2,4,4,4,5,5,7,9]) == 4.0, pstdev == 2.0, variance == 32/7
      assert_in_delta one(conn, "SELECT VAR_POP(v) FROM t"), 4.0, 1.0e-9
      assert_in_delta one(conn, "SELECT STDDEV_POP(v) FROM t"), 2.0, 1.0e-9
      assert_in_delta one(conn, "SELECT VAR_SAMP(v) FROM t"), 32.0 / 7.0, 1.0e-9
      assert_in_delta one(conn, "SELECT STDDEV_SAMP(v) FROM t"), :math.sqrt(32.0 / 7.0), 1.0e-9
    end

    test "NULLs are skipped rather than crashing the aggregate", %{conn: conn} do
      # A deliberate divergence from Django, documented in native/fathom_udf/src/aggregates.rs:
      # Django's `ListAggregate` appends None and `statistics.pstdev` then raises TypeError, so a
      # STDDEV over a nullable column would error the tenant's query. Every other SQL engine skips
      # NULLs, and so do we.
      {:ok, _} = Connection.query(conn, "INSERT INTO t (v) VALUES (NULL)", [])
      assert_in_delta one(conn, "SELECT VAR_POP(v) FROM t"), 4.0, 1.0e-9
    end

    test "degenerate groups are NULL, not an error", %{conn: conn} do
      # statistics.variance raises on fewer than two values; PostgreSQL's var_samp returns NULL.
      assert one(conn, "SELECT VAR_SAMP(v) FROM t WHERE v = 2") == nil
      assert one(conn, "SELECT VAR_POP(v) FROM t WHERE v = 2") == 0.0
      assert one(conn, "SELECT VAR_POP(v) FROM t WHERE v = 999") == nil
      assert one(conn, "SELECT BIT_AND(v) FROM t WHERE v = 999") == nil
    end

    test "bitwise aggregates reduce over the group", %{conn: conn} do
      :ok = Connection.exec(conn, "CREATE TABLE b (v INTEGER)")
      {:ok, _} = Connection.query(conn, "INSERT INTO b (v) VALUES (12),(10)", [])

      assert one(conn, "SELECT BIT_AND(v) FROM b") == 8
      assert one(conn, "SELECT BIT_OR(v) FROM b") == 14
      assert one(conn, "SELECT BIT_XOR(v) FROM b") == 6
    end

    test "ANY_VALUE returns a value from the group", %{conn: conn} do
      value = one(conn, "SELECT ANY_VALUE(v) FROM t")
      assert value in [2, 4, 5, 7, 9]
    end

    test "aggregates work with GROUP BY, not just whole-table", %{conn: conn} do
      {:ok, %{rows: rows}} =
        Connection.query(conn, "SELECT v, COUNT(*), BIT_OR(v) FROM t GROUP BY v ORDER BY v", [])

      assert [[2, 1, 2], [4, 3, 4], [5, 2, 5], [7, 1, 7], [9, 1, 9]] == rows
    end
  end

  describe "NULL propagation" do
    test "a NULL argument yields NULL, not an error", %{conn: conn} do
      nulls = [
        "SELECT LPAD(NULL,3,'0')",
        "SELECT LPAD('x',NULL,'0')",
        "SELECT LPAD('x',3,NULL)",
        "SELECT RPAD(NULL,3,'0')",
        "SELECT REPEAT(NULL,3)",
        "SELECT REVERSE(NULL)",
        "SELECT MD5(NULL)",
        "SELECT SHA256(NULL)",
        "SELECT BITXOR(NULL,1)",
        "SELECT BITXOR(1,NULL)",
        "SELECT COT(NULL)",
        "SELECT django_date_trunc('year',NULL,NULL,NULL)",
        "SELECT django_date_trunc(NULL,'2026-08-05',NULL,NULL)",
        "SELECT django_datetime_trunc('day',NULL,NULL,NULL)",
        "SELECT django_datetime_extract('year',NULL,NULL,NULL)",
        "SELECT django_date_extract('year',NULL)",
        "SELECT django_time_extract('hour',NULL)",
        "SELECT django_time_trunc('hour',NULL,NULL,NULL)",
        "SELECT django_datetime_cast_date(NULL,NULL,NULL)",
        "SELECT django_datetime_cast_time(NULL,NULL,NULL)",
        "SELECT django_time_diff(NULL,'12:00:00')",
        "SELECT django_timestamp_diff(NULL,NULL)",
        "SELECT django_format_dtdelta(NULL,1,2)",
        "SELECT django_format_dtdelta('+',NULL,2)",
        "SELECT regexp(NULL,'abc')"
      ]

      for sql <- nulls do
        assert one(conn, sql) == nil, sql
      end
    end
  end

  # ------------------------------------------------------------------------------------------
  # the wiring: which handles get the functions
  # ------------------------------------------------------------------------------------------

  @tag open_opts: [tenant?: true]
  test "a TENANT handle gets the functions — it is the one that runs Django's SQL", %{conn: conn} do
    # The authorizer set for tenant handles denies ATTACH/DETACH. The extension is loaded BEFORE
    # the authorizer is installed for exactly this reason; if that ordering were reversed these
    # would be missing on the only handle that matters.
    assert one(conn, "SELECT django_date_extract('year','2026-08-05')") == 2026
    assert one(conn, "SELECT MD5('x')") == "9dd4e461268c8034f5c8564e155c67a6"

    assert one(
             conn,
             "SELECT django_datetime_trunc('day','2026-08-05 03:30:00','America/New_York','UTC')"
           ) ==
             "2026-08-04 00:00:00"
  end

  @tag open_opts: [tenant?: true]
  test "loading the extension did not weaken the ATTACH denial", %{conn: conn} do
    # Expert review 2026-08-01 #1. Re-asserted here because this change adds a step to the same
    # configure path, and an ordering mistake that dropped the authorizer would reopen a
    # cross-tenant read/write primitive while every functional test above still passed.
    assert {:error, reason} = Connection.query(conn, "ATTACH DATABASE ':memory:' AS x", [])

    # exqlite surfaces the authorizer's SQLITE_DENY as "not authorized". (The comment in
    # connection.ex says "authorization denied", which is SQLite's concept rather than the string
    # that reaches Elixir — verified against the pre-change code, which returns the same thing.)
    assert inspect(reason) =~ "not authorized"
  end

  test "a READ-ONLY handle gets the functions too", %{path: path, conn: conn} do
    # Seed through the rw handle, then reopen read-only: a :ro stream serves the same Django
    # SELECTs, so missing UDFs there would break exactly the queries a read scope exists for.
    :ok = Connection.exec(conn, "CREATE TABLE t (id INTEGER PRIMARY KEY)")

    {:ok, ro} = Connection.open(path, scope: :ro)
    on_exit(fn -> Connection.close(ro) end)

    assert one(ro, "SELECT django_date_extract('year','2026-08-05')") == 2026
    assert one(ro, "SELECT LPAD('x',3,'0')") == "00x"
  end
end
