defmodule Fathom.DjangoSqlParityTest do
  @moduledoc """
  **The compatibility claim, measured.**

  `native/fathom_udf/tests/oracle/sql_cases.jsonl` is generated by opening a real Python `sqlite3`
  connection, registering Django's UDFs on it exactly as `django/db/backends/sqlite3/base.py` does,
  and running whole queries. That is Django's SQLite backend at the SQL level. This test replays
  every one of those queries through `Fathom.Shard.Connection` — the same code a Hrana stream uses
  — and requires identical rows, cell for cell, **including SQLite's own `typeof()`**.

  ## Why this exists on top of the two function-level oracles

  Those compare functions in isolation. They cannot see:

    * **result types.** `django_format_dtdelta('*', qty, 2)` returning `'6'` as TEXT rather than `6`
      as INTEGER makes `WHERE duration * 2 = 6` match nothing, silently. Every computed cell here
      carries `typeof()`.
    * **which rows come back.** A UDF in a `WHERE` clause decides the result set — the actual
      user-visible behaviour. A `^[a-z0-9-]+$` slug filter returning the wrong rows is what a
      compatibility bug looks like from the application's side.
    * **NULL columns, GROUP BY, ORDER BY** over UDF results.

  ## The two deliberate divergences

  Both are Django *raising* where fathom answers, both are asserted explicitly at the bottom of
  this file rather than tolerated:

    * `STDDEV_POP` over a column containing NULL — Django's aggregate step is `list.append`, so
      `statistics.pstdev` gets a `None` and raises. fathom skips NULLs.
    * `VAR_SAMP` over a single row — `statistics.variance` raises; fathom returns NULL, as
      PostgreSQL does.

  Both make fathom **more permissive**, never less, so no query that works on Django breaks here.
  That direction matters: the reverse would be a compatibility bug.
  """
  use ExUnit.Case, async: false

  alias Fathom.Shard.Connection

  @cases_path Path.expand(
                "../../native/fathom_udf/tests/oracle/sql_cases.jsonl",
                __DIR__
              )

  setup_all do
    path = Path.join(System.tmp_dir!(), "fathom_parity_#{System.unique_integer([:positive])}.db")
    {:ok, conn} = Connection.open(path)

    # The same schema and rows the generator seeded. Kept in the JSONL's own file rather than
    # duplicated here would be better still, but the schema is two statements and drifting them
    # would show up immediately as a wholesale mismatch rather than a subtle one.
    :ok =
      Connection.exec(conn, """
      CREATE TABLE app_order (
        id INTEGER PRIMARY KEY,
        created TEXT,
        due DATE,
        at TIME,
        qty INTEGER,
        price REAL,
        note TEXT,
        span INTEGER
      )
      """)

    {:ok, _} =
      Connection.query(
        conn,
        """
        INSERT INTO app_order (id, created, due, at, qty, price, note, span) VALUES
          (1, '2026-08-05 13:45:59.123456', '2026-08-05', '13:45:59', 3, 1.5, 'alpha',      3600000000),
          (2, '2026-08-05 03:30:00',        '2026-08-04', '03:30:00', 0, 0.0, 'beta' || char(10), 1),
          (3, '2027-01-01 02:00:00',        '2027-01-01', '02:00:00', 7, 2.25, 'Gamma',     86400000000),
          (4, '2024-02-29 12:00:00',        '2024-02-29', '12:00:00', 2, 9.99, 'délta',     -1),
          (5, NULL,                          NULL,         NULL,      NULL, NULL, NULL,     NULL),
          (6, '2026-12-31 23:59:59',        '2026-12-31', '23:59:59', 4, 4.0, 'a-slug-1',   0)
        """,
        []
      )

    on_exit(fn ->
      Connection.close(conn)
      for s <- ["", "-wal", "-shm"], do: File.rm(path <> s)
    end)

    %{conn: conn}
  end

  defp load do
    [meta_line | case_lines] =
      @cases_path
      |> File.read!()
      |> String.split("\n", trim: true)

    {Jason.decode!(meta_line), Enum.map(case_lines, &Jason.decode!/1)}
  end

  # Python's cell encoding -> the Elixir value exqlite returns.
  defp expected_cell(%{"null" => true}), do: :null
  defp expected_cell(%{"int" => n}), do: {:int, n}
  defp expected_cell(%{"float" => f}), do: {:float, f}
  defp expected_cell(%{"text" => s}), do: {:text, s}
  defp expected_cell(%{"blob" => bytes}), do: {:text, :binary.list_to_bin(bytes)}

  defp actual_cell(nil), do: :null
  defp actual_cell(v) when is_integer(v), do: {:int, v}
  defp actual_cell(v) when is_float(v), do: {:float, v}
  defp actual_cell(v) when is_binary(v), do: {:text, v}
  defp actual_cell(v), do: {:other, v}

  defp same?({:float, a}, {:float, b}), do: abs(a - b) <= 1.0e-9 * max(abs(a), max(abs(b), 1.0))
  # SQLite is dynamically typed and the drivers differ on whether an integral REAL comes back as
  # 4 or 4.0. Treated as equal ONLY across int/float, never across text/number — the text-vs-number
  # confusion is the exact bug this file exists to catch.
  defp same?({:int, a}, {:float, b}), do: a * 1.0 == b
  defp same?({:float, a}, {:int, b}), do: a == b * 1.0
  defp same?(a, b), do: a == b

  test "every Django-backend query returns identical rows and types on fathom", %{conn: conn} do
    {meta, cases} = load()
    assert meta["_meta"] == true

    failures =
      Enum.flat_map(cases, fn %{"sql" => sql, "result" => result} ->
        case {result, Connection.query(conn, sql, [])} do
          {%{"error" => kind}, {:ok, _}} ->
            ["#{sql}\n    django raised #{kind}; fathom returned rows"]

          {%{"error" => _}, {:error, _}} ->
            []

          {%{"rows" => _}, {:error, reason}} ->
            ["#{sql}\n    fathom errored: #{inspect(reason) |> String.slice(0, 160)}"]

          {%{"rows" => want_rows}, {:ok, %{rows: got_rows}}} ->
            want = Enum.map(want_rows, fn row -> Enum.map(row, &expected_cell/1) end)
            got = Enum.map(got_rows, fn row -> Enum.map(row, &actual_cell/1) end)

            cond do
              length(want) != length(got) ->
                ["#{sql}\n    row count: django #{length(want)}, fathom #{length(got)}"]

              true ->
                Enum.zip(want, got)
                |> Enum.with_index()
                |> Enum.flat_map(fn {{w, g}, i} ->
                  if length(w) == length(g) and
                       Enum.zip(w, g) |> Enum.all?(fn {a, b} -> same?(a, b) end) do
                    []
                  else
                    [
                      "#{sql}\n    row #{i}: django #{inspect(w)}\n            fathom #{inspect(g)}"
                    ]
                  end
                end)
            end
        end
      end)

    assert failures == [],
           "\n#{length(failures)} of #{length(cases)} Django-backend queries differ on fathom:\n\n" <>
             Enum.join(Enum.take(failures, 15), "\n\n")
  end

  test "the corpus is actually exercising the functions" do
    # A guard on the guard. If the generator ever emitted an empty or trivial corpus this suite
    # would pass having compared nothing.
    {meta, cases} = load()

    assert meta["count"] == length(cases)
    assert length(cases) >= 40

    sql = Enum.map_join(cases, " ", & &1["sql"])

    for fun <- ~w(django_date_extract django_datetime_trunc django_format_dtdelta REGEXP
                  django_datetime_cast_date LPAD MD5 BITXOR django_time_diff) do
      assert String.contains?(sql, fun), "the corpus never exercises #{fun}"
    end

    # And it must contain rows, not just DDL.
    assert Enum.count(cases, fn c -> match?(%{"rows" => [_ | _]}, c["result"]) end) >= 30
  end

  describe "the deliberate divergences — asserted, not tolerated" do
    test "STDDEV_POP over a NULL-containing column answers where Django raises", %{conn: conn} do
      # Django: ListAggregate appends None, statistics.pstdev raises TypeError, which surfaces to
      # the client as OperationalError. Reproducing that faithfully would mean a STDDEV over any
      # nullable column errors the tenant's query.
      assert {:ok, %{rows: [[value]]}} =
               Connection.query(conn, "SELECT STDDEV_POP(qty) FROM app_order", [])

      assert is_float(value)
      assert value > 0.0
    end

    test "VAR_SAMP over one row is NULL where Django raises", %{conn: conn} do
      # statistics.variance needs two values. PostgreSQL returns NULL; so do we.
      assert {:ok, %{rows: [[nil]]}} =
               Connection.query(conn, "SELECT VAR_SAMP(qty) FROM app_order WHERE id = 1", [])
    end

    test "both divergences make fathom MORE permissive, never less" do
      # The direction is the whole argument. A query that works on Django must work here; a query
      # that errors on Django may work here. The reverse would be a compatibility bug.
      {meta, _} = load()

      for d <- meta["divergences"] do
        assert d["django_outcome"] != "ok",
               "#{d["sql"]} no longer raises on Django — this divergence needs re-deciding"
      end
    end
  end
end
