defmodule Mix.Tasks.Fathom.CheckMigrations do
  @shortdoc "CI gate: refuse Django migrations the capture engine cannot see"

  @moduledoc """
  Pre-flight check for Django migrations before they run against the capture template
  (expert review 2026-08-01 #26, third part).

      mix fathom.check_migrations path/to/django/project
      mix fathom.check_migrations path/to/app/migrations --json

  ## What it catches, and why a check is the only option

  A migration with `atomic = False` runs in **autocommit** — outside any tracked `BEGIN…COMMIT` —
  so `Fathom.Migrator.Capture` **cannot see it by construction**. It is not a bug that capture
  misses it; there is no transaction to hook. The template's schema moves and the fleet never
  hears about it.

  The existing gap detector (`migration_gap/1`) catches the *consequence* at the NEXT capture, by
  which point the template is already ahead and that next version is flagged too. So the backstop
  fires late and blames the wrong migration. This runs **before** anything touches the template,
  where the answer is still cheap.

  `atomic = False` is the standard idiom for exactly the long-running migrations a million-shard
  fleet most needs to roll carefully — `AddIndexConcurrently`, chunked backfills — so this is not
  an exotic case to guard against.

  ## Exit codes

  `0` clean, `1` findings. Wire it into CI ahead of `manage.py migrate` against the template.

  ## What it does NOT do

  It does not parse Python. It looks for the `atomic = False` class attribute and for `RunPython` /
  `RunSQL` operations, which are literal, conventional, and generated by Django itself. A lint that
  greps for a known idiom is the proportionate tool here; a Python parser would be a large
  dependency to catch the same three strings.

  `RunPython` is reported as a **warning**, not a failure: it is legitimate and has a supported path
  now (`Fathom.Migrator.attach_transform/2` — see `docs/django-migrations.md`). The point is to tell
  you *before* the fleet freezes that this migration will need one.
  """

  use Mix.Task

  @atomic_false ~r/^\s*atomic\s*=\s*False\s*$/m
  @run_python ~r/\bmigrations\.RunPython\b/
  @run_sql ~r/\bmigrations\.RunSQL\b/

  @impl Mix.Task
  def run(argv) do
    {opts, paths} = OptionParser.parse!(argv, strict: [json: :boolean])

    root =
      case paths do
        [] -> Mix.raise("usage: mix fathom.check_migrations <path> [--json]")
        [p | _] -> p
      end

    unless File.exists?(root), do: Mix.raise("no such path: #{root}")

    findings = root |> migration_files() |> Enum.flat_map(&scan/1)

    if opts[:json] do
      Mix.shell().info(Jason.encode!(%{findings: findings, count: length(findings)}))
    else
      report(findings)
    end

    if Enum.any?(findings, &(&1.severity == "error")) do
      exit({:shutdown, 1})
    end

    :ok
  end

  @doc """
  Scans one migration file. Public so tests drive it directly rather than through a task run.
  """
  @spec scan(Path.t()) :: [map()]
  def scan(path) do
    source = File.read!(path)

    atomic =
      if Regex.match?(@atomic_false, source) do
        [
          %{
            file: path,
            severity: "error",
            rule: "atomic_false",
            message:
              "`atomic = False` runs in autocommit, so fathom's capture engine cannot see this " <>
                "migration at all — the template moves ahead and the fleet never hears. Remove it, " <>
                "or apply this migration to every shard out of band and reconcile the directory."
          }
        ]
      else
        []
      end

    data =
      cond do
        Regex.match?(@run_python, source) ->
          [
            %{
              file: path,
              severity: "warning",
              rule: "run_python",
              message:
                "`RunPython` writes cross the wire as the TEMPLATE's literal row values, so " <>
                  "capture flags the version and the rollout holds. Supported path: keep the DDL " <>
                  "here, drop the data step, and express the backfill as a " <>
                  "Fathom.Migrator.Transform attached with attach_transform/2."
            }
          ]

        Regex.match?(@run_sql, source) ->
          [
            %{
              file: path,
              severity: "warning",
              rule: "run_sql",
              message:
                "`RunSQL` is replayed verbatim on every tenant. That is correct for DDL and wrong " <>
                  "for anything carrying literal row values — check which this is."
            }
          ]

        true ->
          []
      end

    atomic ++ data
  end

  @doc "Every Django migration file under `root` (skips `__init__.py`)."
  @spec migration_files(Path.t()) :: [Path.t()]
  def migration_files(root) do
    cond do
      File.regular?(root) ->
        [root]

      true ->
        root
        |> Path.join("**/migrations/*.py")
        |> Path.wildcard()
        |> Enum.concat(Path.wildcard(Path.join(root, "*.py")))
        |> Enum.uniq()
        |> Enum.reject(&(Path.basename(&1) == "__init__.py"))
        |> Enum.sort()
    end
  end

  defp report([]) do
    Mix.shell().info([:green, "fathom.check_migrations: clean"])
  end

  defp report(findings) do
    for f <- findings do
      colour = if f.severity == "error", do: :red, else: :yellow

      Mix.shell().info([
        colour,
        "#{f.severity}: #{f.file} [#{f.rule}]",
        :reset,
        "\n  #{f.message}"
      ])
    end

    errors = Enum.count(findings, &(&1.severity == "error"))
    warnings = length(findings) - errors
    Mix.shell().info("\n#{errors} error(s), #{warnings} warning(s)")
  end
end
