import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :fathom, FathomWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at COMPILE-time (runtime overrides abort boot), so the
# insecure-local escape hatch is compile-time too: WEB_INSECURE_LOCAL is a BUILD-time env set only
# by the chaos rig / a plaintext LAN demo — it turns off SSL forcing + the LiveView WS origin check
# so a browser on the LAN can reach the plaintext dashboard. NEVER build a real deployment with it.
if System.get_env("WEB_INSECURE_LOCAL") in ~w(1 true) do
  config :fathom, FathomWeb.Endpoint, force_ssl: false, check_origin: false
else
  config :fathom, FathomWeb.Endpoint,
    force_ssl: [rewrite_on: [:x_forwarded_proto]],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
end

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
