defmodule Fathom.Rebalancer.LbMap do
  @moduledoc """
  Renders the LB exception table into an nginx snippet the load balancer `include`s: a
  `map $host $fathom_target` layered on the consistent-hash pool, plus one pin-upstream
  per backend node.

  The base LB config keeps `upstream fathom_hrana { hash $host consistent; ... }` and does
  `proxy_pass http://$fathom_target;`. For a pinned shard the map resolves `$fathom_target`
  to that node's pin upstream; every other host falls through to `default fathom_hrana` and
  stays on the pure hash. So the exception is *only* the hot minority — the pure-hash story
  holds for everything else.

  ## Dead-pin failover (finding #1)

  Each pin upstream lists the pinned node as the primary `server` and **every other backend
  as a `backup`** server. While the pinned node is up, all pinned traffic concentrates on it
  (backups idle). When it dies, nginx (`max_fails`/`fail_timeout`) fails the pin over to a
  surviving backend — which cold-opens the shard and steals the lease (the dead owner's
  heartbeat is stale), exactly as a non-pinned shard would re-hash on death. Without the
  backups a single-server pin turns its shard from self-healing into "down until an operator
  unpins it" — worse the more shards the rebalancer has moved. The `{owner, epoch}` lease
  still arbitrates single-writer across the failover.

  Pure and deterministic (overrides are rendered shard-sorted), so it is fully unit-tested
  and a re-render with unchanged inputs is byte-identical (a no-op reload).
  """

  alias Fathom.Rebalancer
  alias Fathom.Rebalancer.Overrides

  @doc """
  Renders the current exception table (from `Overrides.all/0`, `Rebalancer.lb_backends/0`,
  and `:shard_base_domain`) into the nginx snippet.
  """
  @spec current() :: String.t()
  def current do
    render(Overrides.all(), Rebalancer.lb_backends(), base_domain())
  end

  @doc """
  Pure render: `overrides` (each with `.shard_id`/`.pinned_node`), the backend set
  `%{node_key => address}`, and the base domain → the nginx snippet. Overrides whose
  `pinned_node` isn't a known backend are skipped (never point the map at a missing
  upstream).
  """
  @spec render([map()], %{optional(String.t()) => String.t()}, String.t()) :: String.t()
  def render(overrides, backends, base_domain) do
    entries =
      overrides
      # Skip failed/reverted rows (finding #4): they're retained only as a cooldown record,
      # so the shard routes via the hash home (source), not the target it failed to move to.
      |> Enum.reject(&Map.get(&1, :failed_at))
      # Defense-in-depth (finding #14): never emit a raw shard_id into the nginx map key
      # unless it passes Fathom.ShardId (mirrors the skip-unknown-backend filter below).
      |> Enum.filter(&Fathom.ShardId.valid?(&1.shard_id))
      |> Enum.filter(&Map.has_key?(backends, &1.pinned_node))
      |> Enum.sort_by(& &1.shard_id)
      |> Enum.map_join("\n", fn o ->
        "    #{o.shard_id}.#{base_domain} #{upstream_name(o.pinned_node)};"
      end)

    sorted = Enum.sort_by(backends, fn {node, _addr} -> node end)

    upstreams =
      Enum.map_join(sorted, "\n\n", fn {node, addr} ->
        # The pinned node is primary; every other backend is a `backup` so nginx fails a
        # dead pin over to a survivor (which steals the stale lease). Backups sorted for a
        # byte-identical re-render.
        backups =
          sorted
          |> Enum.reject(fn {n, _addr} -> n == node end)
          |> Enum.map_join("", fn {_n, addr} -> "\n    server #{addr} backup;" end)

        "upstream #{upstream_name(node)} {\n    server #{addr} max_fails=2 fail_timeout=10s;#{backups}\n    keepalive 16;\n}"
      end)

    map_body = if entries == "", do: "", else: "\n" <> entries

    """
    # Generated by Fathom.Rebalancer.LbMap — do not edit by hand.
    # The exception table: pinned subdomains route to a node's pin-upstream; everything
    # else falls through to `default fathom_hrana` (the consistent-hash pool).
    map $host $fathom_target {
        default fathom_hrana;#{map_body}
    }

    #{upstreams}
    """
  end

  # An nginx upstream name for a node_key: [a-zA-Z0-9_] only (an IP like 10.0.0.12 → a
  # legal identifier), so the same key always renders to the same upstream name.
  @doc false
  @spec upstream_name(String.t()) :: String.t()
  def upstream_name(node_key) do
    "fathom_pin_" <> String.replace(node_key, ~r/[^a-zA-Z0-9_]/, "_")
  end

  defp base_domain do
    (Application.get_env(:fathom, :shard_base_domain) || "fathom.test")
    |> to_string()
  end
end
